// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Background struct {
	Name string `db:"name" json:"name"`
	Desc string `db:"desc" json:"desc"`
}

type Character struct {
	ID               int64       `db:"id" json:"id"`
	Owner            int64       `db:"owner" json:"owner"`
	Name             string      `db:"name" json:"name"`
	Race             interface{} `db:"race" json:"race"`
	Background       interface{} `db:"background" json:"background"`
	Alignment        interface{} `db:"alignment" json:"alignment"`
	Experience       int64       `db:"experience" json:"experience"`
	StrenghtProf     bool        `db:"strenght_prof" json:"strenghtProf"`
	DexterityProf    bool        `db:"dexterity_prof" json:"dexterityProf"`
	ConstitutionProf bool        `db:"constitution_prof" json:"constitutionProf"`
	IntelligenceProf bool        `db:"intelligence_prof" json:"intelligenceProf"`
	WisdomProf       bool        `db:"wisdom_prof" json:"wisdomProf"`
	CharismaProf     bool        `db:"charisma_prof" json:"charismaProf"`
	ArmorClass       int64       `db:"armor_class" json:"armorClass"`
	MaxHp            int64       `db:"max_hp" json:"maxHp"`
	CurrentHp        int64       `db:"current_hp" json:"currentHp"`
	TempHp           int64       `db:"temp_hp" json:"tempHp"`
	DeathSuccess     int64       `db:"death_success" json:"deathSuccess"`
	DeathFail        int64       `db:"death_fail" json:"deathFail"`
	Proficencies     interface{} `db:"proficencies" json:"proficencies"`
	Equipment        interface{} `db:"equipment" json:"equipment"`
	CoinsCopper      int64       `db:"coins_copper" json:"coinsCopper"`
	CoinsSilver      int64       `db:"coins_silver" json:"coinsSilver"`
	CoinsElectrum    int64       `db:"coins_electrum" json:"coinsElectrum"`
	CoinsGold        int64       `db:"coins_gold" json:"coinsGold"`
	CoinsPlatinum    int64       `db:"coins_platinum" json:"coinsPlatinum"`
	Personality      interface{} `db:"personality" json:"personality"`
	Ideals           interface{} `db:"ideals" json:"ideals"`
	Bonds            interface{} `db:"bonds" json:"bonds"`
	Flaws            interface{} `db:"flaws" json:"flaws"`
}

type CharacterClass struct {
	Character int64          `db:"character" json:"character"`
	Class     int64          `db:"class" json:"class"`
	Subclass  sql.NullString `db:"subclass" json:"subclass"`
	Level     int64          `db:"level" json:"level"`
}

type CharacterScore struct {
	ID        int64       `db:"id" json:"id"`
	Score     string      `db:"score" json:"score"`
	Character int64       `db:"character" json:"character"`
	Value     int64       `db:"value" json:"value"`
	Operation interface{} `db:"operation" json:"operation"`
}

type CharacterSkill struct {
	Character int64  `db:"character" json:"character"`
	Skill     string `db:"skill" json:"skill"`
	Prof      bool   `db:"prof" json:"prof"`
	Expert    bool   `db:"expert" json:"expert"`
}

type CharacterSpeed struct {
	ID        int64       `db:"id" json:"id"`
	Character int64       `db:"character" json:"character"`
	Value     int64       `db:"value" json:"value"`
	Type      interface{} `db:"type" json:"type"`
	Operation interface{} `db:"operation" json:"operation"`
}

type Class struct {
	Name string `db:"name" json:"name"`
}

type Race struct {
	Name string `db:"name" json:"name"`
	Desc string `db:"desc" json:"desc"`
}

type Score struct {
	Name string `db:"name" json:"name"`
}

type Skill struct {
	Name  string `db:"name" json:"name"`
	Score string `db:"score" json:"score"`
}

type User struct {
	ID     int64       `db:"id" json:"id"`
	Name   string      `db:"name" json:"name"`
	Passwd []byte      `db:"passwd" json:"-"`
	Salt   []byte      `db:"salt" json:"-"`
	Role   interface{} `db:"role" json:"role"`
}
